/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.wary.app

import org.junit.jupiter.api.Assertions.assertDoesNotThrow
import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class AppTest {
    @Test fun testValidateFeedback() {
        assertEquals("", validateFeedback(listOf("f", "soare", "10002"), 5))
    }
}
